### ISSUE TITLE
Icon Request:

### ISSUE THREAD

**Issue by Derick1530** [praveenjuge/mynaui-icons#2]
**Icon Name:** 
Name of the icon
message-square-reply

**Describe the icon:**
Explain the icon you'd like to see, and potential use-cases.

**Any tags you can think of:**
Tags are useful for searching the icon.

**Additional context:**
Add any other context or screenshots about the icon request here.
<img width="336" alt="image" src="https://github.com/praveenjuge/mynaui-icons/assets/61876679/d5fa78a9-90b9-4fc6-b36d-c005499c27d8">

**Comment by praveenjuge** [comment]
Thanks for the request, this is added: https://icons.mynaui.com/icons/message-reply/
