### ISSUE TITLE
Icon Request: Rocket

### ISSUE THREAD

**Issue by Derick1530** [praveenjuge/mynaui-icons#3]
**Icon Name:** 
Name of the icon
rocket
**Describe the icon:**
Explain the icon you'd like to see, and potential use-cases.

**Any tags you can think of:**
Tags are useful for searching the icon.

**Additional context:**
Add any other context or screenshots about the icon request here.
<img width="559" alt="image" src="https://github.com/praveenjuge/mynaui-icons/assets/61876679/6148eb6a-3f4e-4f13-83c8-843f94605f53">

**Comment by praveenjuge** [comment]
Thanks for the request, this is added: https://icons.mynaui.com/icons/rocket/
