### ISSUE TITLE
Request for Filled Icons

### ISSUE THREAD

**Issue by imfunniee** [praveenjuge/mynaui-icons#4]
First of all, I'd like to say that the current set of icons is outstanding! Clean! ✨

That said, I wanted to inquire if there are any plans to introduce filled versions of these icons. Is this something that might be on the roadmap or considered for future updates?

Thanks for all your great work!

**Comment by praveenjuge** [comment]
Thanks!

Yes that's in plan, here is the roadmap I'm working on right now:

- designing like 30 more line icons
- better search in mynaui.com/icons
- filled version for all the icons

**Comment by imfunniee** [comment]
Hi Praveen,

Thank you for the update and for sharing the roadmap! 😊 We’re excited to see the new developments, especially the filled versions of the icons.

I hope I'm not being too forward, but I wanted to ask if there’s an estimated timeline for when the filled versions might be available. We’re planning to integrate these icons into our app soon and it would be incredibly helpful to know if we can expect the filled versions sometime soon.

Thanks again for all the hard work and for considering this request!

**Comment by praveenjuge** [comment]
No problem! It's great to hear you are considering using this icon pack.

I have already started to work on filled version, here is a sneak peak:

<img width="500" alt="Icons" src="https://github.com/user-attachments/assets/2db1d957-c82b-4909-8e67-9d2720b6705d">

I'm expecting it to be published on 30th September. Hope this helps!

**Comment by imfunniee** [comment]
![WoahPoGIF](https://github.com/user-attachments/assets/6375e02e-d75c-4217-a415-d596c670ad8d)

**Comment by sourinsarkar** [comment]
I was finding ways to reach you regarding filled icons, and then I found this. Waiting for those.

**Comment by praveenjuge** [comment]
@imfunniee @sourinsarkar The filled icons are pushed in https://mynaui.com/icons, I'm still working on some bug fixes for that, after pushing that will close this issue!

**Comment by praveenjuge** [comment]
🎉 Released in [v0.3.1](https://github.com/praveenjuge/mynaui-icons/releases/tag/v0.3.1) 🎉
