### ISSUE TITLE
Regular icons font is broken?

### ISSUE THREAD

**Issue by bgalartza** [praveenjuge/mynaui-icons#7]
**Describe the bug**
We are trying to use the regular icons via the Font files, but it looks like there is something wrong. 

**To Reproduce**
1. Download [mynaui.woff Font file](https://github.com/praveenjuge/mynaui-icons/blob/v0.3.2/packages/icons/mynaui.woff)
2. Open with Fonts Inspector (in my case Gnome Font Types)
3. Icons don't look like in the examples

We also tried loading the fonts in the browser (using the CSS provided the package), but they look the same.

**Expected behavior**
The icons to look like in the examples.

**Screenshots**
In Gnome Font view:
![image](https://github.com/user-attachments/assets/abdcc657-3451-4c26-becd-9e3e64b04ec5)

Loading the home in the browser. Expected vs what we see:
![image(1)](https://github.com/user-attachments/assets/04772a07-3a77-4276-9499-c7bf3c4fd22a)
![image](https://github.com/user-attachments/assets/1a36babf-8779-4e3b-b529-f757dd79a90f)

**Desktop (please complete the following information):**
 - OS: "Debian GNU/Linux 12 (bookworm)
 - Browser Firefox and Chrome

Thanks in advance

**Comment by praveenjuge** [comment]
Fixing soon!

**Comment by praveenjuge** [comment]
Thanks for reporting this! This should be fixed in [v0.3.3](https://github.com/praveenjuge/mynaui-icons/releases/tag/v0.3.3).

Let me know if something is wrong!

![Screenshot 2024-11-25 at 12 20 20 AM](https://github.com/user-attachments/assets/3af259fa-130f-455f-ac63-2d9011cc6c79)

**Comment by bgalartza** [comment]
That was fast! Looks great now. Thank you very much
